server {
  listen 80;
  server_name localhost;
  
  # Serve the Angular app
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # Proxy requests to backend
  location /backend/ {
    proxy_pass http://backend-service/;
  }

  location /cfgi {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /dominance {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

}