apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 4002
      targetPort: 4002
  selector:
    app: frontend
