apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"         
        prometheus.io/port: "8080"            
        prometheus.io/path: "/metrics"       
    spec:
      containers:
        - name: frontend
          image: superuserdo/cryptoinsight_frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health*
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health 
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20

