services:
  influxdb:
    image: jihadhd/influxdb:latest
    build: ./database

  datastreaming:
    image: jihadhd/datastream:latest
    build: ./dataStreamer

  backend:
    image: jihadhd/backend:latest
    build: ./backend

  frontend:
    image: jihadhd/frontend:latest
    build: ./frontend
