services:
  influxdb:
    image: europe-west12-docker.pkg.dev/dev-guild-439910-e9/cryptoinsight-docker/influxdb:latest
    build: ./database

  datastreaming:
    image: europe-west12-docker.pkg.dev/dev-guild-439910-e9/cryptoinsight-docker/datastreaming:latest
    build: ./dataStreamer

  backend:
    image: europe-west12-docker.pkg.dev/dev-guild-439910-e9/cryptoinsight-docker/backend:latest
    build: ./backend

  frontend:
    image: europe-west12-docker.pkg.dev/dev-guild-439910-e9/cryptoinsight-docker/frontend:latest
    build: ./frontend
