apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: jihadhd/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "4Gi"
            limits:
              memory: "6Gi"
              cpu: "750m"
              ephemeral-storage: "4Gi"
          readinessProbe:
                    httpGet:
                      path: /
                      port: 8080
                    periodSeconds: 5
                    timeoutSeconds: 60 
                    successThreshold: 1
                    failureThreshold: 3
                    initialDelaySeconds: 70      
          livenessProbe:
                    httpGet:
                      path: /
                      port: 8080
                    periodSeconds: 5
                    timeoutSeconds: 60
                    successThreshold: 1
                    failureThreshold: 3          
                    initialDelaySeconds: 70
