apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: sre
data:
  prometheus.rules: |-
    groups:
      - name: Memory Alert
        rules:
          - alert: High Pod Memory
            expr: sum(container_memory_usage_bytes) > 7516192768
            for: 1m
            labels:
              severity: slack
            annotations:
              summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets:
              - 'localhost:8080'
              - 'localhost:8081'
      - job_name: 'data_pipeline'
        static_configs:
          - targets: 
              - 'influxdb-service.default.svc.cluster.local:8080'
