{
 "title": "Kube State Metrics v2",
 "description": "This Grafana dashboard provides a comprehensive overview of the state and performance of Kubernetes resources within your cluster, with a focus on resource counts, utilization, and availability. It covers key metrics across nodes, namespaces, pods, and containers, making it easier to monitor and troubleshoot your cluster effectively.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   { "name": "datasource", "query": "Prometheus" },
   { "name": "resolution", "label": "Resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Memory consumption by namespace",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\",namespace=\"$namespace\"}) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Consumption SRE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\",namespace=\"sre\"}) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\",namespace=\"sre\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{cluster=\"$cluster\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{cluster=\"$cluster\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" },
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total pods" }
   ]
  },
  {
   "title": "Cluster Pod Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})/ sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "Limited"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",resource=\"memory\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Limited"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Not Ready - Node's",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"false\"}==1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Pressure",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Pod's Restart in 30 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_reason{namespace=~\"$namespace\", reason=\"Evicted\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "HPA",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "Total HPA Current",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 115 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\",cluster=~\"$cluster\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 115 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  }
 ]
}