apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: sre
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  selector:
    app: monitoring-stack
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
