# A service account is used to let apps interact with the Kubernetes API
# In our case we use this app to monitor ressources so we need to interact with the API
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: admin
  namespace: sre
