apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastreaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastreaming
  template:
    metadata:
      labels:
        app: datastreaming
    spec:
      containers:
        - name: datastreaming
          image: datastreaming:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: TOPIC
              value: "assets"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: datastreaming-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: datastreaming
