apiVersion: v1
kind: Service
metadata:
  name: datastreaming-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30200
  selector:
    app: datastreaming
