apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-port-internal
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-port-external
      protocol: TCP
      port: 9094
      targetPort: 9094
  type: LoadBalancer
