server {
  listen 80;
  server_name localhost;
  
  location / {
    proxy_pass http://frontend:80/;
  }

  location /backend/ {
    proxy_pass http://backend:8080/;
  }

  location /cfgi {
    proxy_pass http://frontend:80/;
  }

  location /dominance {
    proxy_pass http://frontend:80/;
  }

  location /api/v2/global/ {
    proxy_pass https://api.alternative.me/v2/global/;
  }
}