name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u jihadhd --password-stdin

      - name: Build Docker Images
        run: docker-compose build

      - name: Push Docker Images
        run: docker-compose push

      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCLOUD_AUTH }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform (Cluster)
        run: terraform apply -target=google_container_cluster.primary -lock=false -auto-approve

      - name: Apply Terraform (Full)
        run: terraform apply -lock=false -auto-approve
