name: Deploy Kubernetes Cluster and Pods

on:
  push:
    branches:
      - terraform
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      # Step 3: Configure gcloud CLI and Authenticate
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Step 5: Apply Terraform to create the cluster
      - name: Apply Terraform - Create Cluster
        run: terraform apply -target=google_container_cluster.primary -auto-approve
        working-directory: terraform

      # Step 6: Apply Terraform to deploy pods
      - name: Apply Terraform - Deploy Pods
        run: terraform apply -auto-approve
        working-directory: terraform
